//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocaXavierExamenUF2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciclista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ciclista()
        {
            this.etapas = new HashSet<etapa>();
            this.llevars = new HashSet<llevar>();
            this.puertoes = new HashSet<puerto>();
        }
    
        public short dorsal { get; set; }
        public string nombre { get; set; }
        public Nullable<short> edad { get; set; }
        public string nomeq { get; set; }
    
        public virtual equipo equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etapa> etapas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<llevar> llevars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<puerto> puertoes { get; set; }
    }
}
