//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocaXavierExamenUF2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class etapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public etapa()
        {
            this.llevars = new HashSet<llevar>();
            this.puertoes = new HashSet<puerto>();
        }
    
        public short netapa { get; set; }
        public Nullable<short> km { get; set; }
        public string salida { get; set; }
        public string llegada { get; set; }
        public short dorsal { get; set; }
    
        public virtual ciclista ciclista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<llevar> llevars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<puerto> puertoes { get; set; }
    }
}
