//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocaXavierExamenUF2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class maillot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maillot()
        {
            this.llevars = new HashSet<llevar>();
        }
    
        public string codigo { get; set; }
        public string tipo { get; set; }
        public string color { get; set; }
        public Nullable<int> premio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<llevar> llevars { get; set; }
    }
}
