//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocaXavierExamenUF2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class puerto
    {
        public string nompuerto { get; set; }
        public Nullable<short> altura { get; set; }
        public string categoria { get; set; }
        public Nullable<double> pendiente { get; set; }
        public short netapa { get; set; }
        public short dorsal { get; set; }
    
        public virtual ciclista ciclista { get; set; }
        public virtual etapa etapa { get; set; }
    }
}
